# Generated by Django 3.1.4 on 2021-01-11 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField(blank=True, null=True, verbose_name='Цена от')),
                ('max_price', models.IntegerField(blank=True, null=True, verbose_name='До')),
                ('min_area', models.IntegerField(blank=True, null=True, verbose_name='Минимальная площадь (кв. метров)')),
                ('max_area', models.IntegerField(blank=True, null=True, verbose_name='Максимальная площадь (кв. метров)')),
                ('min_room_count', models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество комнат')),
                ('max_room_count', models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество комнат')),
                ('min_floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж от')),
                ('max_floor', models.IntegerField(blank=True, null=True, verbose_name='До')),
                ('min_floor_count', models.IntegerField(blank=True, null=True, verbose_name='Количество этажей от')),
                ('max_floor_count', models.IntegerField(blank=True, null=True, verbose_name='До')),
                ('property_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Тип имущества')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор обьявления')),
            ],
            options={
                'verbose_name': 'запрос',
                'verbose_name_plural': 'запросы',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('address', models.CharField(blank=True, max_length=15, null=True, verbose_name='Адрес')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('floor_count', models.IntegerField(blank=True, null=True, verbose_name='Количество этажей')),
                ('property_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Тип собственности')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор обьявления')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
