# Generated by Django 3.1.4 on 2021-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('address', models.CharField(max_length=15, verbose_name='Адрес')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('floor_count', models.IntegerField(verbose_name='Количество этажей')),
                ('property_type', models.CharField(max_length=15, verbose_name='Тип собственности')),
            ],
        ),
    ]
