# Generated by Django 3.1.4 on 2021-01-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='floor_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='property_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Тип собственности'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество комнат'),
        ),
    ]
