# Generated by Django 3.1.4 on 2021-01-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='ID клиента')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Телефонный номер')),
                ('email', models.CharField(max_length=30, verbose_name='Почта')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(verbose_name='ID предложения')),
                ('requirement_id', models.IntegerField(verbose_name='ID запроса')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='ID клиента')),
                ('realtor_id', models.IntegerField(verbose_name='ID риелтора')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('address', models.CharField(max_length=25, verbose_name='Имя')),
                ('floor', models.IntegerField(verbose_name='Номер этажа')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('area', models.IntegerField(verbose_name='Площадь (кв. метров)')),
                ('floor_count', models.IntegerField(verbose_name='Количество этажей')),
                ('type_of_property', models.CharField(max_length=15, verbose_name='Тип имущества')),
                ('coordinates', models.CharField(max_length=100, verbose_name='Координаты')),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtor_id', models.IntegerField(verbose_name='ID риелтора')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('email', models.CharField(max_length=30, verbose_name='Почта')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
                ('comission', models.IntegerField(verbose_name='Комиссия')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.IntegerField(verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='ID клиента')),
                ('realtor_id', models.IntegerField(verbose_name='ID риелтора')),
                ('min_price', models.IntegerField(verbose_name='Цена от')),
                ('max_price', models.IntegerField(verbose_name='До')),
                ('min_area', models.IntegerField(verbose_name='Минимальная площадь (кв. метров)')),
                ('max_area', models.IntegerField(verbose_name='Максимальная площадь (кв. метров)')),
                ('min_room_count', models.IntegerField(verbose_name='Минимальное количество комнат')),
                ('max_room_count', models.IntegerField(verbose_name='Максимальное количество комнат')),
                ('min_floor', models.IntegerField(verbose_name='Этаж от')),
                ('max_floor', models.IntegerField(verbose_name='До')),
                ('min_floor_count', models.IntegerField(verbose_name='Количество этажей от')),
                ('max_floor_count', models.IntegerField(verbose_name='До')),
                ('type_of_property', models.CharField(max_length=15, verbose_name='Тип имущества')),
            ],
        ),
    ]
